org: tosadvisor
app: image-optimize
service: image-optimize
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    binaryMediaTypes:
      - '*/*'
      - 'image/*'

functions:
  optimize:
    handler: handler.optimize
    events:
      - http:
          path: optimize
          method: get
  readme:
    handler: handler.readme
    events:
      - http:
          path: readme.md
          method: get

plugins:
  - serverless-offline

